// Generated by Selenium IDE
package RBT;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC1VPTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  static String pathToChromeexe ="D:\\RBTs\\RBTSelenium27Feb\\chromedriver110\\chromedriver.exe";
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver",pathToChromeexe );
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC1VP() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1040, 652));
    assertThat(driver.getTitle(), is("Google"));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("Spain");
    driver.findElement(By.cssSelector("form > div:nth-child(1)")).click();
    //driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
    assertThat(driver.getTitle(), is("Spain - Google Search"));
    driver.close();
  }
}
