// Generated by Selenium IDE
package SeleniumIde;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC02WeatherinHyderabadVPTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeSuite
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver","D:\\sel\\temp\\chromedriver_win32\\chromedriver.exe" );
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterSuite
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC02WeatherinHyderabadVP() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("Weather in hyderabad");
    driver.findElement(By.cssSelector(".ikrT4e")).click();
    
   // driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
    //driver.findElement(By.id("wob_loc")).click();
   // assertThat(driver.getTitle(), is("Weather in hyderabad - Google Search"));
    driver.close();
  }
}
